### ISSUE TITLE
sound as well?

### ISSUE THREAD

**Issue by talkingtab** [claudetech/koa-stream#2]
Thanks for the work, its great and I finally got streaming to work, but I'm not getting sound. I basically just took the example that uses this statement
`yield stream.file(this, 'filter.mp4', {root: '/tmp/videos'});`

but no sound.
Thanks

**Comment by talkingtab** [comment]
Looks like I used the one movie clip without sound. User error 42

**Comment by danhper** [comment]
Glad it worked for you 😄
